inveniosoftware/invenio-records-files

.travis.yml, CHANGES.rst, RELEASE-NOTES.rst, invenio_records_files/version.py, setup.py, tests/conftest.py
=> release: v1.0.0a1

AUTHORS.rst, invenio_records_files/version.py
=> version: post-release bump

invenio_records_files/models.py, tests/conftest.py, tests/test_models.py
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> models: cascade action on record delete

AUTHORS.rst, invenio_records_files/jsonschemas/__init__.py, invenio_records_files/jsonschemas/records-files/records-files-v1.0.0.json, setup.py
* Adds a JSON schema for files.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> schema: initial JSON schema

AUTHORS.rst, CHANGES.rst, RELEASE-NOTES.rst, invenio_records_files/version.py
=> release: v1.0.0a2

CHANGES.rst, RELEASE-NOTES.rst, invenio_records_files/version.py
=> release: v1.0.0a3

CHANGES.rst, RELEASE-NOTES.rst, invenio_records_files/__init__.py, invenio_records_files/api.py, invenio_records_files/models.py, invenio_records_files/version.py, tests/conftest.py, tests/test_invenio_records_files.py
=> global: fixes and v1.0.0a4

docs/conf.py
=> docs: ReadTheDocs in intersphinx config

CHANGES.rst, RELEASE-NOTES.rst, invenio_records_files/version.py
=> release: v1.0.0a7

docs/api.rst, invenio_records_files/mappings/__init__.py, invenio_records_files/mappings/records-files/records-files-v1.0.0.json, invenio_records_files/receivers.py, setup.py, tests/test_invenio_records_files.py
* Adds new receiver for automatic fulltext indexing.
Co-authored-by: Salvatore Zaza <salvatore.zaza@gmail.com>
Co-authored-by: Rémi Ducceschi <remi.ducceschi@gmail.com>
--
addresses https://github.com/inveniosoftware/invenio-indexer/issues/46
=> receivers: attachement indexer

.travis.yml, docs/conf.py, invenio_records_files/utils.py, setup.py, tests/conftest.py, tests/test_utils.py
* Moves utility function `file_download_ui` from Invenio-Files-REST.
(addresses inveniosoftware/invenio-files-rest#135)
=> global: moving of file_download_ui

.travis.yml, invenio_records_files/alembic/1ba76da94103_create_records_files_tables.py, invenio_records_files/alembic/2da9a03b0833_create_records_files_branch.py, setup.py
=> global: initial alembic recipes

invenio_records_files/alembic/1ba76da94103_create_records_files_tables.py, setup.cfg, setup.py, tests/conftest.py, tests/test_invenio_records_files.py
(closes [#41](https://github.com/inveniosoftware/invenio-records-files/issues/41))
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>
=> alembic: addition of dependency to invenio-records

CHANGES.rst, RELEASE-NOTES.rst, invenio_records_files/version.py
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>
=> release: v1.0.0a9

invenio_records_files/api.py, tests/test_invenio_records_files.py
Minimal reproduction for a bug that popped out from our Sentry: https://travis-ci.org/inveniosoftware/invenio-records-files/jobs/306347184#L956.
=> api: support unicode filenames

CHANGES.rst, RELEASE-NOTES.rst, invenio_records_files/utils.py, invenio_records_files/version.py, setup.py, tests/conftest.py, tests/test_utils.py
Depends on the unreleased https://github.com/inveniosoftware/invenio-files-rest/commit/74846ed4468365c72db6e18c34c9818c3ace5c34
=> utils: add "download" parameter to UI view

docs/requirements.txt
=> docs: adding missing sqlite dependency

README.rst
=> docs: adding list of features to README

invenio_records_files/__init__.py
=> docs: add Integration with invenio-records-ui

tests/data/v6/records-files/records-files-v1.0.0.json
=> tests: remove _attachment from schema

docs/conf.py, invenio_records_files/__init__.py
=> docs: review, intersphinx_mapping fix & typos

invenio_records_files/jsonschemas/records-files/records-files-v1.0.0.json, tests/data/v6/records-files/records-files-v1.0.0.json
=> add file_id to json schema

docs/configuration.rst, docs/index.rst, invenio_records_files/__init__.py, invenio_records_files/api.py, invenio_records_files/config.py, invenio_records_files/ext.py, invenio_records_files/views.py, setup.py, tests/conftest.py, tests/test_models.py, tests/test_views.py
* Closes #71
* Closes https://github.com/inveniosoftware/invenio-records-files/issues/55
=> views: implementation of records_files views

invenio_records_files/__init__.py
=> docs: fix curl example

invenio_records_files/__init__.py, invenio_records_files/utils.py
* A few minor fixes. Closes #90
=> docs: review
